### ISSUE TITLE
Generate documentation for controller

### ISSUE THREAD

**Issue by smadapathi** [Quramy/generator-ngdoc#1]
I am unable to generate documentation for controller and I did not find any example as well on how to do it. 

```
/**
 *
 * @ngdoc controller
 * @name RuleTypeListController
 * @description
 * This is a sample controller
 *
 **/
```

When I do like above, it says "TypeError: Cannot call method 'indexOf' of undefined"

**Comment by Quramy** [comment]
Hi @smadapathi .

`@ngdoc` annotation must not be `controller`.

If you want write document of some controllers, you can use `@ngdoc type`.
(For example, see [AngularJS form controller's source](https://github.com/angular/angular.js/blob/master/src/ng/directive/form.js#L21))

**Comment by smadapathi** [comment]
Thank you very much!
